// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api from "./routes/api.tsx";
import * as $films from "./routes/films.tsx";
import * as $getFilm_id_ from "./routes/getFilm/[_id].tsx";
import * as $index from "./routes/index.tsx";
import * as $noProjects from "./routes/noProjects.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $DeleteFilm from "./islands/DeleteFilm.tsx";
import * as $DeleteProject from "./islands/DeleteProject.tsx";
import * as $Main from "./islands/Main.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api.tsx": $api,
    "./routes/films.tsx": $films,
    "./routes/getFilm/[_id].tsx": $getFilm_id_,
    "./routes/index.tsx": $index,
    "./routes/noProjects.tsx": $noProjects,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/DeleteFilm.tsx": $DeleteFilm,
    "./islands/DeleteProject.tsx": $DeleteProject,
    "./islands/Main.tsx": $Main,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
